### ISSUE TITLE
Direction-less agent

### ISSUE THREAD

**Issue by HugoChateauLaurent** [maximecb/gym-minigrid#124]
Hi, is it possible to create a grid with an agent that directly tries to move forward in the direction of the action?

**Comment by maximecb** [comment]
Hi Hugo,

You'd have to modify the logic for how the agent moves, which is contained here: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L1099

You can also add new actions, eg: up, down, left, right, by modifying this enumeration: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L629

It shouldn't be too hard, except the logic for pickup and drop will need to be adjusted since there would no longer be a cell that is "in front" of the agent. You might also want to change the drawing code so the agent is no longer a triangle pointing in a given direction. Let me know if you need more pointers on how to do this.
