### ISSUE TITLE
Question on the FullyObservableWrapper 

### ISSUE THREAD

**Issue by ErikVester** [maximecb/gym-minigrid#127]
Hi, 

Thank you for this great project! 
I am currently experimenting with the FullyObservableWrapper - with the rl-starter-files repo - and I am running into some problems. On problems where the original version - with partial observability - learns reasonably quick (around 300k frames) the fully observable version does not seem to learn at all, also when I run it for even more frames. This for instance happens on the doorkey environments. 

I looked into some previous issues and realised that others seemed to have this problem before as well and suggested some changes to the wrapper, but I am not sure if these changes were added already. 

If anyone knows how to fix this, please let me know! I will start looking into it myself as well, but I am still relatively new to all this so it might be that I am just simply missing something :) 

Kind regards,

Erik

**Comment by maximecb** [comment]
Hi Erik,

If you have any insight into how to make this work, I'd be curious. I would start by experimenting with the smallest possible version of the environment.

So far, as far as I can tell, full observability is just harder than partial observability. It makes some amount of sense because with full observability, the action to take is dependent on the position of the agent. Each position and direction leads to a different action needing to be taken. In contrast, with partial observability, the agent can often act simply by reacting to what it sees in the cells it is looking at. I think that partial observability leads to policies that generalizes better.

**Comment by ErikVester** [comment]
Hi Maxime, 

One thing I have figured out is that, as Driesssens mentioned previously as well I think, with the current FullyObservableWrapper there is no encoding of the object that the agent is currently carrying. This could be added by adding another element in the lib of observations? I need a a single Box shaped observation for my experiments, so I will try to make a combination of this and the FlatObsWrapper.
