### ISSUE TITLE
API to obtain goal location

### ISSUE THREAD

**Issue by happyhackingit** [maximecb/gym-minigrid#136]
Is there a way to know the location of goal? After browsing the code, it seems to me that there is no easy way to know where the goal is. Wondering if the developers could point out a way to obtain it? Thanks!

**Comment by happyhackingit** [comment]
Could the authors of mini-grid point out a way to obtain the goal location? It seems that the goal is actually placed by [place_obj function](https://github.com/maximecb/gym-minigrid/blob/b08fa6a058adcab0a78f1c923be05125f085f4e2/gym_minigrid/minigrid.py#L890) but I do not know how to retrieve the location. Thank you!

**Comment by maximecb** [comment]
Hello @happyhackingit,

As of now there is no direct way to retrieve the location. It's assumed that you will train a neural network that will learn how to navigate to it based on vision.

In order to keep track of the location, you could either store the location when the goal gets added in `place_obj`, or you could write a method that iterates over the grid, eg something like:

```
for i in env.grid.width:
    for j in env.grid.height:
        tile = env.grid.get(i, j):
            if tile instanceof Goal:
                env.goal_pos = (i, j)
```

**Comment by happyhackingit** [comment]
Hi @maximecb, I see, thank you! super helpful. It seems to me that it would be better that if there is API to retrieve the given goal and to set arbitrary new goal. There are many use cases in goal-based RL.

**Comment by maximecb** [comment]
Well, the problem is that environments could have more than one goal.

I think it would be trivial to implement what you want. You can add a function that does `env.grid.set(i, j, goal_object)` and stores the goal location, and if there is already a goal location store, you move it to a different location.
