### ISSUE TITLE
How to duplicate the current env

### ISSUE THREAD

**Issue by donamin** [maximecb/gym-minigrid#153]
Hi,

Thanks for the awesome repo.
I have a question though: Is there anyway for duplicating the current grid state? I'm trying to implement a MCTS agent that can operate in this environment and for that, I need to be able to forward simulate the environment by duplicating the current env.

Cheers
Amin

**Comment by maximecb** [comment]
Hi Amin!

I think you may be able to just use the copy.deepcopy() method on the env directly:
https://docs.python.org/3/library/copy.html

Otherwise env.grid definitely is copyable that way, but you might have to implement your own copy method for the MiniGridEnv class:
https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L369
