### ISSUE TITLE
Upstreaming to Gym

### ISSUE THREAD

**Issue by jkterry1** [maximecb/gym-minigrid#154]
Hey, I'm the new maintainer of Gym. 

I've recently been trying to curate environments in Gym to be representative of good and important environments for the community, especially for beginners to look at, so far mostly by pulling out environments that are no longer generally used or good ideas.

Minigrid is unique in that it's the only environment outside of Gym that I'm aware of that has risen to the level of community importance that the major classic environment in Gym like mountain car or Barto and Sutton's blackjack have. Given this, what would you think of upstreaming this environment to be a part of Gym, specifically in the toy_text environment class?

**Comment by maximecb** [comment]
Hello Terry,

Congratulations on your new position as maintainer of OpenAI Gym. The invitation to upstream MiniGrid is flattering and interesting, though I do have some concerns.

At the moment people have been citing this repository, which means I do get some credit for the work of creating the environment (ie: https://scholar.google.com/citations?user=lSg6I8gAAAAJ&hl=en). If MiniGrid is upstreamed into OpenAI Gym, I think people could end up just citing OpenAI Gym, which would kind of erase my contribution.

My other concern is in terms of keeping the environment alive and keeping it true to the original vision. Much of the code in the world of deep learning has (in my opinion) too many dependencies and is very fragile because of that. I've been very careful to minimize dependencies and to avoid feature creep (meaning refusing some feature additions). I believe that's been a major contributor to the success of MiniGrid: it just works everywhere. If MiniGrid was to be upstreamed, I would hope that it remains more or less the same. Adding new environments is fine, but I don't really want to see lots of new features added.

Then there's also the issue of deprecation. I will keep this environment alive and functioning for as long as possible, but could I be guaranteed that if it were upstreamed, someone would not eventually decide to just deprecate and delete it?

**Comment by jkterry1** [comment]
Hey,

First of all, you'd still be the maintainer of this environment, it would just live in Gym. Many different environments or sets of environments in Gym have official or de-facto maintainers who are not myself.

In Gym, your repository could not be cited directly, you'd have to write a short white paper on Arxiv and ask for that to be cited instead. There are environments in Gym that commonly do this, e.g. people cite the Atari papers when using those environments or Barto and Sutton when using environments that come from that and so on. We're currently in the process of adding a new and detailed documentation website that will make the appropriate citations for different environments super clear. There's also a good chance that including it in Gym would bring a lot of new people into using your environment. You can also mark this and your two(?) google scholar entries for this repo as being the same work so that the citations add up.

Gym environments generally do not accept new features (tons have been turned down) and the comparable environments (take a look at those in toy_text or classic_control) have comparably few dependencies. The goal is to have a standard minimal repository of environments that are widely useful. The only feature requests I'm really interested in in general are ones that add arguments to make environments more configurable without having to fork the code. One small change I'd like to make though is to rename this to "minigrid" instead of "gym-minigrid" (for what should be obvious reasons)

Gym historically has not really deprecated environments. It's basically only ever happened when I've done it recently, and the only environments I've removed are ones that are not used and realistically should not have been included in the first place (e.g. ones where you can teach the RL to do addition and multiplication) or ones that have had to be replaced with very similar environments due to dependency/maintenance reasons (e.g. the MuJuCo environments are being replaced with ones that depend on Brax). Neither of those really apply here; as long as simple grid world environments are useful/important teaching or benchmarking tools in RL, this will stay in Gym.

**Comment by maximecb** [comment]
> Gym environments generally do not accept new features (tons have been turned down)

That seems like a good thing 👍 

> We're currently in the process of adding a new and detailed documentation website that will make the appropriate citations for different environments super clear.

Can you tell me what is the timeline on that? I might prefer to wait until said website is ready if you are ok with that. At which point we could transfer the existing MiniGrid documentation there.

If you're ok with waiting a little bit, I think I could go forward with this plan. I would just like the website you mention to be up. I could then write a short whitepaper and put it on arxiv, and we could do the renaming and upstreaming. I would only take down this repo once everything has been completed, and maybe even wait a bit after, so that there is no downtime for anyone currently using this environment. I could maybe even add some harder environments, since apparently they have all been solved now :)

**Comment by jkterry1** [comment]
"I'm not sure toy_text is right because none of those environments have graphics. Minigrid is more like a little game, and some of the environments have no text observations at all."

I don't want to create a new class of environment's just for this and I think that toy_text is close enough to work. I'd also like to add non-terminal rendering to the three remaining toy_text environments that's similar to minigrid. What can be included in toy_text has always been an incredibly loose boundary.

"Can you tell me what is the timeline on that?"
Roughly another month, hopefully. We've been working on it for the past month and thought it would take a month to do, but it turns out that web dev is hard. And ya I'm fine waiting for that.

"Maybe I could take this opportunity to correct a small design flaw. "
That sounds like it'd be fairly helpful, yes :). If there are any others doing them before merging into Gym would be good because once it's in Gym we have to bump version numbers and so on.

**Comment by jkterry1** [comment]
One thing that we'll need from you to integrate it into the Gym documentation website is an .md documentation file, it'll look like this: https://github.com/PettingZoo-Team/PettingZoo/blob/master/docs/butterfly/pistonball.md

**Comment by maximecb** [comment]
Ok contacting you.
