### ISSUE TITLE
Env from text file

### ISSUE THREAD

**Issue by d3sm0** [maximecb/gym-minigrid#40]
Here we discuss the possibility of creating a simple environment from txt file. Few consideration first:

1. The gym interface doesn't allow for extra argument in gym.make, how can we handle this? 
2. The core method should be already present in `MiniGridEnv.__str__`.
3. How diverse can be the set of environment from txt file

My suggestion would be "invert" the __str__ function, and use the same dictionary to generate the grid, with 1 character for each pixel indicating the type of the object and complete the rendering with the default color.

Regarding 1. maybe a wrapper that recreate the enviornment taking the path of the text file as argument?

**Comment by maximecb** [comment]
I agree that if there is a text-based format, it should mirror the format from the `__str__` method. We may want to change the symbols used to represent the agent though, as they are non-ASCII and hard to type on a keyboard.

For creating envs with parameters, the way to do this is to import them directly, eg: `from minigrid.envs import TextFileEnv(file_name)`.

I'm going to ask the obvious question though: do you personally have a need for this feature? Would you make use of it. Because it's not that hard to create environments just by writing code, so unless you actually have a legitimate use for this, I would say YAGNI?

**Comment by d3sm0** [comment]
> I agree that if there is a text-based format, it should mirror the format from the `__str__` method. We may want to change the symbols used to represent the agent though, as they are non-ASCII and hard to type on a keyboard.
> 
> For creating envs with parameters, the way to do this is to import them directly, eg: `from minigrid.envs import TextFileEnv(file_name)`.
> 
> I'm going to ask the obvious question though: do you personally have a need for this feature? Would you make use of it. Because it's not that hard to create environments just by writing code, so unless you actually have a legitimate use for this, I would say YAGNI?

Thanks it seems like we do need this feature.

**Comment by maximecb** [comment]
One thing we should do for this feature is have some round-trip testing. Grid to text, then parse the text back into a grid, and make sure the two versions are identical. I would implement all of the __str__ and parsing functionality into the grid class. That will also require us to treat agents as world objects, in order to parse the agent position as well.

**Comment by maximecb** [comment]
Closing for now.
