### ISSUE TITLE
Introducing Dynamic Obstacles to the Empty Environment

### ISSUE THREAD

**Issue by Suman7495** [maximecb/gym-minigrid#50]
Hi,

I want to introduce Dynamic Obstacles to the Empty Environment (`MiniGrid-Empty`). This could be represented by a moving colored square on the grid. The objective of the robot would be to navigate without colliding with these dynamic obstacles.

Moreover, I also want to introduce occlusion. If an obstacle lies in front of the robot, and another obstacle lies directly behind the first obstacle, the second obstacle should be hidden by the first one, i.e. the robot fails to see the 2nd obstacle.

The final environment will be similar to the Lava Crossing Environment with the following changes:
1) Each obstacles (lava) is only 1 cell size.
2) Motion of obstacle is random.
3) Obstacle occlusion.

To achieve these tasks, could you kindly point me to the files to be modified?

Thank you

**Comment by maximecb** [comment]
Hi Suman,

The empty environment is implemented here: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/envs/empty.py

The rest of the logic you are looking for is in minigrid.py: https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py

In particular, the `process_vis` function computes a visibility mask, the cells that are visible to the agent. It basically propagates visibility forward until a wall or closed door is hit.

For moving obstacles, if you just want one environment, I would suggest overriding the `step` function in your new environment class. Keep track of your moving object, and update its position using `self.grid.set(i, j, object)`. Since the motion of your obstacle is random, you will likely want to use the `self.env._rand_int()` method. This will ensure that you always get the same behavior in your environment given the same seed.

Let me know if you have any other questions.

**Comment by Suman7495** [comment]
Thank you for your perfect guidelines.

I was able to successfully add a new environment with Dynamic Obstacles. This environment will be used for research at TU Darmstadt testing novel RL algorithms for mobile robot navigation with dynamic obstacles. [Here](https://github.com/Suman7495/gym-minigrid.git) is the link to the branch. I have added a short description of the environment in the README under the section of "Dynamic obstacles environment".

It may be useful to merge this branch with the master for future robotics research.

Thank you.

**Comment by maximecb** [comment]
Well done! I would be happy to merge it if you create a pull request :)

**Comment by Suman7495** [comment]
I will do it soon. I just found a small bug. I'll rectify it and get back to you.

**Comment by Suman7495** [comment]
To randomly generate obstacles I have the following:
`        for i_obst in range(n_obstacles):
            self.obstacles.append(Obstacle())
            self.place_obj(self.obstacles[i_obst], max_tries=100)`

While this works in `manual_control.py`, it fails in `run_tests.py` with the error:  `RecursionError: rejection sampling failed in place_obj`.

I can't seem to pinpoint the issue.

**Comment by Suman7495** [comment]
I have created the pull request :)
