### ISSUE TITLE
Minigrid.place_obj only avoiding agent start_pos

### ISSUE THREAD

**Issue by andreicnica** [maximecb/gym-minigrid#66]
Hi! While looking at the method I saw that it is only checking the agent _start_pos_ and not the current _agent_pos_. I can suggest a fix with a pull request if it was not intentional (it will also affect the Dynamic-Obstacles envs as it was counting that it could place an object on top of the agent and then check for overlap - so have to fix this as well if it changes).

```
            # Don't place the object where the agent is
            if np.array_equal(pos, self.start_pos):
```
[Ref code](https://github.com/maximecb/gym-minigrid/blob/511e71676f86e0950208736a1720949156cb3b4a/gym_minigrid/minigrid.py#L935)

By the way great job with the envs. Thank you!

**Comment by maximecb** [comment]
Right, that should be fixed, however, you have to be a little careful, because `agent_pos` may not yet be set when `place_obj` is called. Ideally, both `start_pos` and `agent_pos` should be reset to None before `_gen_grid` is called here:

https://github.com/maximecb/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L726

**Comment by maximecb** [comment]
I just pushed a fix that removes `start_pos` and always uses `agent_pos` instead. I think this makes the code simpler, and it eliminates this problem.
