### ISSUE TITLE
Old obstacles positions in observation from env.step() in Dynamic-Obstacles environment

### ISSUE THREAD

**Issue by fedem96** [maximecb/gym-minigrid#79]
Hello, I found a problem in the Dynamic-Obstacles environment.
The problem is that in env.step(action), the obstacles position is updated after calling the env.step() of the base class, and the observation is not updated with the new position of the obstacles. So, the returned observation by env.step() has the obstacles in the old position.

Example:
`obs, reward, done, info = env.step(action)  # in obs, obstacles are in the old position`
`pixmap = env.render('pixmap')    # in pixmap, obstacles are in the new (correct) position`

Workaround: manual update observation after env.step()
`obs, reward, done, info = env.step(action)`
`obs = env.gen_obs()`

Suggested fix:
In _dynamicobstacles.py_, change the return after the obstacles positions update from:
`return obs, reward, done, info`
to:
`return self.gen_obs(), reward, done, info`

**Comment by maximecb** [comment]
Thanks for reporting this issue. There have been a number of problems with this environment. Hopefully this is the last bug :sweat_smile:

I don't love the idea of generating the observation twice because it will slow down the simulation. I think we can fix this bug by inverting the logic. That is, we update the obstacle positions before calling the parent step function. Then, the agent only gets punished if it tries to walk over an obstacle, which is as before. The difference is that the obstacles get priority with respect to movement. If the agent tries to move forward, sometimes a moving obstacle will get in its way before it can move. However, the agent is still in control of whether it reaches the goal or not.

I just pushed a commit implementing this. Let me know if it works for you or not. Note that your minigrid seems to be a bit out of date. There is a new renderer using numpy, no more pyqt and no more pixmaps. Hope that does not pose an issue either.

**Comment by fedem96** [comment]
Thanks for the quick reply, now the observation is consistent with the render.

As you noted, now the agent is sometimes blocked by the obstacles: if you want to avoid this behavior, you can replace the line:
`self.place_obj(self.obstacles[i_obst], top=top, size=(3,3), max_tries=100)`
with:
`self.place_obj(self.obstacles[i_obst], top=top, size=(3,3), max_tries=100, reject_fn=lambda this, pos: all(this.front_pos == pos))`

As for my version, I use the latest v1.0.1 from pypi, so the pixmap is a numpy array: the 'pixmap' string is there since I previously used the QT render. Anyway, thank you!
