### ISSUE TITLE
New kind of tiles/objects ?

### ISSUE THREAD

**Issue by AMairesse** [maximecb/gym-minigrid#88]
Hello,

I've been using gym-minigrid for a personal project and I need to add new kind of tiles/objects.
For example I'm adding a FoodSource object, which produce Food around. The agent have an energy level and doing actions use energy. Taking Food add energy to the agent.

My question is : are you interested in pull-requests for new kind of tiles/objects or do you prefer to keep gym-minigrid as it is ?

Thanks a lot for your work !
Antoine.

**Comment by maximecb** [comment]
Hi Antoine. It depends how clean well-factored your implementation is. I may be ok with new objects, but in general I prefer to not add extra features to the MiniGridEnv class itself, because everyone has custom needs for their research, and it could quickly become incomprehensible.

That being said, if all you're doing is adding one new object type and some environments using that object, it may be fine. Would have to see a pull request.

Best,
Maxime

**Comment by AMairesse** [comment]
Ok, thanks. I'll keep that in mind and if my project give interesting results I will try a pull request.
