### ISSUE TITLE
Floor object doesn't render

### ISSUE THREAD

**Issue by ChaceAshcraft** [maximecb/gym-minigrid#90]
I added colored floor tiles to one of your environments and it failed to render:

`self.grid.set(i, j, Floor(color=self._rand_elem(colors)))`
```
  File "site-packages/gym/core.py", line 233, in render
    return self.env.render(mode, **kwargs)
  File "gym-minigrid/gym_minigrid/minigrid.py", line 1279, in render
    highlight_mask=highlight_mask if highlight else None
  File "gym-minigrid/gym_minigrid/minigrid.py", line 527, in render
    tile_size=tile_size
  File "gym-minigrid/gym_minigrid/minigrid.py", line 469, in render_tile
    obj.render(img)
  File "gym-minigrid/gym_minigrid/minigrid.py", line 177, in render
    r.setLineColor(100, 100, 100, 0)
AttributeError: 'numpy.ndarray' object has no attribute 'setLineColor'
```
Am I using them wrong? Thanks!

**Comment by maximecb** [comment]
Hi there @ChaceAshcraft 

You're not doing anything wrong. The issue is that I reimplemented the renderer a few months ago to eliminate the PyQT dependency, and I never fixed the floor tiles. This highlights the problem that there is currently no environment that uses the floor tiles, so this never got tested. That makes me think we should fix this bug and also create a simple environment using floor tiles.

**Comment by ChaceAshcraft** [comment]
Thanks for getting back to me! That sounds awesome!

**Comment by maximecb** [comment]
I've fixed the rendering of the floor tile. If you end up creating an environment using them and you think it could make sense to open a PR, please do so :)
